# Usa un'immagine base Python
FROM python:3.9-slim

# Imposta la directory di lavoro
WORKDIR /app

# Copia i file necessari nel container
COPY sim/main.py /app/main.py
COPY sim/port.py /app/port.py
COPY sim/templates/index.html /app/templates/index.html

# Installa Flask e Flask-CORS
RUN pip install Flask Flask-Cors

# Esponi le porte necessarie
EXPOSE 8080 8083

# Comando di avvio
CMD ["python3", "main.py"]