version: '3.8'

services:
  application:
    build:
      context: ./DOLLY
      dockerfile: Dockerfile.application
    container_name: application
    ports:
      - "8080:8080"
    environment:
      DOCKER_HOST_IP: host.docker.internal

  scenario:
    build:
      context: ./scenario
      dockerfile: Dockerfile.scenario
    container_name: scenario
    ports:
      - "8081:8081"
    environment:
      DOCKER_HOST_IP: host.docker.internal
    depends_on:
      - application