services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=camunda-bpm,ldap
      - CAMUNDA_BPM_ADMIN_USER=admin
      - CAMUNDA_BPM_ADMIN_PASSWORD=admin
    networks:
      - camunda-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - camunda-network

  optimize:
    image: camunda/optimize:3.12.12
    container_name: optimize
    depends_on:
      - camunda
      - elasticsearch
    ports:
      - "8090:8090"
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://camunda:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=elasticsearch
      - OPTIMIZE_ELASTICSEARCH_HTTP_PORT=9200
    networks:
      - camunda-network

networks:
  camunda-network:
    driver: bridge